remote_theme: just-the-docs/just-the-docs
logo: "/assets/images/logo-black.png"
title: Open World Server
baseurl: ""
repository: Dartanlla/OWS
url: "http://openworldserver.com/"
github_username:  Dartanlla

aux_links:
  "GitHub":
    - "//github.com/Dartanlla/OWS"